const fs = require('fs');
const content = fs.readFileSync('/Users/daveconnors/wordgames/letterpress/src/data/wordList_clean.ts', 'utf8');

// Extract existing words
const existing = new Set(content.match(/"([a-z]+)"/g).map(w => w.replace(/"/g, '')));

// Additional common 5-letter words to add for better coverage and connectivity
const additionalWords = [
  // Common Wordle-style words and everyday vocabulary
  "abbey", "abort", "absorb", "abuse", "aches", "adapt",
  "adder", "aging", "agree", "aisle",
  // More A words
  "alien", "alley", "allow", "alone", "alpha", "amend", "amine", "amino",
  "angle", "annex", "annoy", "aorta", "apron", "arise",
  // Common B words missing
  "badge", "balmy", "bands", "banks", "barge", "barns", "bases",
  "baste", "bated", "bathe", "baton", "beads", "beady", "beaks",
  "beams", "beans", "bears", "beats", "beech", "beers", "befit",
  "beige", "belly", "belts", "bills", "bites", "blare", "blaze",
  "blobs", "blown", "blows", "blues", "boats", "boggy", "borax",
  "bowed", "bower", "boxer", "boxes", "brace", "braid", "brash",
  "brass", "brawn", "braze", "briny", "brisk", "brute", "bugle",
  "built", "burly", "burnt", "buses",
  // Common C words missing
  "cache", "caddy", "cages", "cairn", "caked", "cakes", "calms",
  "cameo", "canoe", "caper", "carat", "cared", "cares", "carol",
  "cases", "caves", "cells", "cents", "chafe", "champ", "chaps",
  "chewy", "chick", "chili", "chime", "chins", "chips", "chirp",
  "choir", "cinch", "circa", "clads", "clamp", "clams", "clang",
  "clank", "claps", "clasp", "claws", "clays", "clips", "clods",
  "clogs", "clone", "clown", "cluck", "clump", "coals", "coats",
  "cocoa", "coded", "codes", "colds", "colon", "colts", "combo",
  "comes", "comfy", "comma", "conch", "condo", "cones", "coops",
  "coped", "copes", "copse", "cords", "cores", "corny", "costs",
  "count", "coupe", "coves", "cribs", "cries", "crops", "cruet",
  "crumb", "crust", "cubic", "cuffs", "cumin", "curds", "cured",
  "curls", "curly",
  // Common D words missing
  "daddy", "dally", "dared", "darts", "dates", "datum", "dawns",
  "dealt", "death", "debit", "debut", "decal", "decry", "deems",
  "deity", "delve", "demur", "diets", "digit", "dimly", "dined",
  "discs", "dives", "docks", "doves", "drags", "drips", "drugs",
  "duels", "duets", "dulls", "dunks", "duped", "dwelt", "dying",
  // Common E words missing
  "eager", "eagle", "early", "earth", "ebony", "edged", "edits",
  "eerie", "elfin", "email", "emoji", "enact", "endow", "eying",
  // Common F words missing
  "faces", "faded", "fades", "fears", "feels", "feuds", "fills",
  "films", "fined", "fists", "flags", "flaps", "flaws", "flick",
  "flips", "fluff", "foams", "fools", "fouls", "fries", "frisk",
  "frock", "frogs", "fuels", "fumes", "fuses",
  // Common G words missing
  "gaped", "gates", "gazed", "gazer", "geeks", "genie", "germs",
  "girls", "gnash", "glyph", "gonna", "graze", "grimy", "grist",
  "grobs", "grubs",
  // Common H words missing
  "hacks", "haiku", "halts", "hares", "hated", "hater", "hauls",
  "hawks", "heirs", "hiker", "hilly", "hives", "homer",
  // Common I words missing
  "idled", "imago", "impel", "ingot",
  // Common J words missing
  "jenny", "jimmy", "junco",
  // Common K words missing
  "keels", "kicks", "kills", "kinds", "kings", "kites", "knees",
  "knits",
  // Common L words missing
  "laces", "lacks", "laden", "ladle", "lasts", "lawns", "leaks",
  "licks", "lifts", "liked", "likes", "limps", "lions", "loafs",
  "lured", "lurks",
  // Common M words missing
  "manga", "maths", "maven", "melts", "mince", "minds", "mined",
  "moans", "moldy", "mowed",
  // Common N words missing
  "napes", "nests", "nodal",
  // Common O words missing
  "outed",
  // Common P words missing
  "panda", "pasty", "paths", "paves", "plier", "plods", "polyp",
  "posse", "pouty",
  // Common Q-R words missing
  "quasi", "radii", "radon", "ramps", "rarer", "raspy", "reams",
  "recon", "remit", "renal", "reuse", "roams", "robes", "roman",
  "roofs", "rooms", "rouge", "rumba", "rungs",
  // Common S words missing
  "sacks", "seals", "seeks", "sells", "sends", "sepia", "serif",
  "sewed", "shire", "sinew", "skimp", "slink", "slows", "slunk",
  "smock", "spiel", "spans", "sprig", "suits",
  // Common T words missing
  "tails", "tamed", "tangy", "teary", "teddy", "thrum", "tilts",
  "tolls", "trots",
  // Common U-V words missing
  "umbra", "unfed", "unzip", "vulva",
  // Common W words missing
  "wills", "weald", "whiff", "whims", "whiny",
  // Common Y-Z words missing
  "yanks", "yours", "zappy", "zippy", "zoned",

  // Additional high-connectivity words (common patterns)
  "bakes", "canes", "dates", "fakes", "gates", "hates", "lakes",
  "makes", "names", "rakes", "rates", "takes", "wakes", "wales",
  "wines", "wires", "tires", "fires", "hires", "mires", "sires",
  "wires", "dines", "fines", "lines", "mines", "pines", "vines",
  "bonds", "fonds", "ponds", "wands", "bands", "hands", "lands",
  "sands", "brain", "chain", "drain", "grain", "plain", "slain",
  "spain", "stain", "swain", "train",
  "black", "clack", "crack", "knack", "shack", "slack", "smack",
  "snack", "stack", "track", "whack",
  "blade", "blaze", "blame", "brave", "crave", "crane", "grade",
  "grape", "grate", "grave", "image", "phase", "place", "plane",
  "plate", "prize", "shade", "shake", "shame", "shape", "share",
  "shave", "skate", "slate", "snake", "space", "spade", "spare",
  "stage", "stake", "stale", "stare", "state", "trade", "whale",
  "blank", "bland", "brand", "grand", "gland", "plant", "slant",
  "stand",
  "bleed", "breed", "creed", "freed", "greed", "speed", "steed",
  "treed",
  "blew", "brew", "chew", "crew", "drew", "flew", "grew", "knew",
  "stew",
  "blind", "blink", "brink", "cling", "climb", "drink", "grind",
  "print", "sling", "slink", "spine", "spill", "split", "sting",
  "stiff", "still", "stint", "strip", "swing", "thing", "think",
  "thinl", "trick", "twirl", "twist", "whirl",
  "block", "clock", "flock", "knock", "shock", "smock", "stock",
  "bloom", "broom", "gloom", "groom",
  "blown", "brown", "clown", "crown", "drown", "frown", "grown",
  "shown", "shorn", "sworn", "thorn",
  "board", "hoard", "gourd",
  "boast", "coast", "roast", "toast",
  "boost", "ghost", "frost", "roost",
  "bound", "found", "hound", "mound", "pound", "round", "sound",
  "wound",
  "brace", "grace", "place", "space", "trace",
  "brass", "class", "crass", "glass", "grass",
  "bread", "dread", "tread", "shred", "dread", "spread",
  "break", "freak", "sneak", "speak", "steak", "tweak", "wreak",
  "bring", "cling", "fling", "sling", "sting", "swing", "thing",
  "wring",
  "brood", "flood", "stood", "blood",
  "brook", "crook", "shook",
  "brush", "blush", "crush", "flush", "plush",
  "build", "child", "guild", "yield",
  "cabin", "chain", "claim", "drain", "grain", "plain", "Spain",
  "stain", "train",
  "catch", "hatch", "latch", "match", "patch", "watch",
  "cause", "gauge", "pause", "sauce",
  "chair", "flair",
  "chant", "giant", "grant", "plant", "slant",
  "charm", "alarm",
  "chase", "erase", "phase",
  "cheap", "clear", "clean", "cream", "dream", "gleam", "shear",
  "smear", "spear", "steam", "swear", "treat", "tread",
  "check", "cheek", "creek", "sleek",
  "chest", "crest", "quest",
  "child", "chill",
  "chose", "close", "those", "whose",
  "chunk", "drunk", "flunk", "plunk", "shrunk", "skunk", "spunk",
  "stunk", "trunk",
  "cider", "elder", "hider", "rider", "tiger", "timer", "tower",
  "wider",
  "climb", "crimp",
  "cloth", "sloth",
  "cloud", "aloud", "proud", "shroud",
  "coach", "poach", "roach",
  "color", "dolor", "honor", "humor", "labor", "manor", "mayor",
  "minor", "motor", "tenor", "tutor", "vigor",
  "coral", "focal", "local", "modal", "moral", "naval", "nodal",
  "pedal", "penal", "renal", "rival", "royal", "rural", "tidal",
  "tonal", "total", "trial", "usual", "vital", "vocal",
  "could", "mould", "would", "should",
  "count", "fount", "mount", "shout", "snout", "spout", "stout",
  "trout",
  "court", "short", "snort", "sport",
  "cover", "hover", "lover", "mover", "rover", "Dover",
  "craft", "draft", "graft", "shaft",
  "crash", "brash", "clash", "flash", "gnash", "slash", "smash",
  "stash", "trash",
  "creek", "cheek", "sleek",
  "crime", "grime", "prime", "slime",
  "cross", "floss", "gloss",
  "crowd", "rowdy",
  "dance", "fancy", "lance", "ranch", "prance",
  "drink", "brink", "think", "shrink",
  "drive", "strive", "thrive",
  "earth", "dearth", "hearth",
  "every", "fever", "lever", "never", "sever",
  "faith", "filth",
  "feast", "least", "beast", "yeast",
  "field", "yield", "wield", "shield",
  "fight", "light", "might", "night", "right", "sight", "tight",
  "bight", "eight",
  "final", "penal", "renal", "rival", "tidal", "trial", "viral",
  "vital",
  "first", "thirst", "burst", "worst",
  "flame", "blame", "frame", "shame",
  "flesh", "fresh", "pleat", "bleat", "cleat", "sweat", "wheat",
  "float", "bloat", "gloat",
  "floor", "flour",
  "force", "gorge", "forge",
  "forth", "north", "worth",
  "found", "bound", "hound", "mound", "pound", "round", "sound",
  "wound",
  "fresh", "flesh", "crush", "brush",
  "front", "blunt", "brunt", "grunt", "shunt", "stunt",
  "frost", "ghost",
  "glass", "brass", "class", "crass", "grass",
  "globe", "glove", "grove", "prove", "stove",
  "going", "being", "doing", "dying", "lying", "tying",
  "grand", "brand", "gland", "bland", "stand",
  "grass", "brass", "class", "crass", "glass",
  "green", "sheen", "queen",
  "greet", "fleet", "sheet", "sleet", "sweet", "tweet",
  "guide", "pride",
  "happy", "sappy", "snappy",
  "heart", "smart", "start",
  "heavy", "gravy", "navy",
  "hedge", "ledge", "wedge",
  "horse", "house", "mouse", "goose", "loose", "moose", "noose",
  "index", "latex",
  "inner", "diner",
  "ivory",
  "joint", "moist", "point",
  "juice", "price", "slice", "spice", "twice", "voice",
  "kneel", "steel", "wheel",
  "knife", "strife",
  "known", "blown", "brown", "clown", "crown", "drown", "frown",
  "grown", "shown", "shorn", "sworn", "thorn",
  "laser", "later", "layer", "maser", "mater", "rater", "water",
  "leave", "heave", "weave",
  "level", "lever", "never", "sever",
  "light", "fight", "might", "night", "right", "sight", "tight",
  "eight",
  "linen", "liver", "liter",
  "loose", "goose", "moose", "noose",
  "lover", "cover", "hover", "mover", "rover",
  "lower", "bower", "mower", "power", "tower", "tower", "sower",
  "magic", "manic", "basic", "sonic", "tonic", "toxic", "topic",
  "match", "catch", "hatch", "latch", "patch", "watch",
  "metal", "medal", "modal", "pedal", "petal",
  "model", "modem", "motel", "novel", "panel", "towel", "vowel",
  "money", "honey",
  "month", "mouth", "mirth", "mourn", "south", "youth",
  "movie", "motor", "model",
  "music", "manic", "basic", "magic", "panic", "tonic", "toxic",
  "never", "fever", "lever", "sever",
  "night", "fight", "light", "might", "right", "sight", "tight",
  "eight",
  "noise", "poise",
  "north", "forth", "worth",
  "offer", "other", "after", "alter", "utter", "outer", "under",
  "order", "older",
  "outer", "utter", "other",
  "paint", "faint", "joint", "point", "print", "saint",
  "panel", "model", "motel", "novel", "towel", "vowel",
  "paper", "caper", "viper",
  "party", "pasty", "patty", "petty", "piety", "potty",
  "peace", "peach", "place",
  "phone", "ozone", "stone", "prone",
  "piece", "price", "spice",
  "plant", "chant", "giant", "grant", "slant",
  "plate", "skate", "slate", "state",
  "point", "faint", "joint", "paint", "print", "saint",
  "pound", "bound", "found", "hound", "mound", "round", "sound",
  "wound",
  "power", "lower", "mower", "tower",
  "press", "bless", "chess", "dress", "gross", "guess", "stress",
  "price", "grace", "juice", "piece", "slice", "spice", "trace",
  "twice", "voice",
  "pride", "bride", "guide", "glide", "slide", "stride",
  "prime", "crime", "grime", "slime",
  "print", "faint", "joint", "paint", "point", "saint",
  "prize", "graze",
  "proud", "cloud",
  "prove", "above", "glove", "grove", "stove",
  "queen", "green", "sheen",
  "quick", "brick", "click", "flick", "prick", "slick", "stick",
  "thick", "trick",
  "quiet", "quilt",
  "quite", "quote", "wrote",
  "raise", "chase", "erase", "phase", "rinse",
  "range", "mange", "orange",
  "reach", "beach", "leach", "peach", "teach",
  "react", "exact", "tract",
  "ready", "beady", "heady", "needy", "reedy", "seedy", "weedy",
  "right", "fight", "light", "might", "night", "sight", "tight",
  "eight",
  "river", "diver", "giver", "liver",
  "robin", "resin", "satin", "basin", "cabin",
  "rocks", "docks", "locks", "mocks", "socks",
  "round", "bound", "found", "hound", "mound", "pound", "sound",
  "wound",
  "route", "flute", "brute",
  "saint", "faint", "joint", "paint", "point", "print",
  "scale", "shale", "stale", "whale",
  "scene", "scone",
  "sense", "dense", "fence", "hence", "rinse", "tense",
  "serve", "nerve", "verge", "verse",
  "seven", "given", "liven", "raven", "woven",
  "shake", "brake", "drake", "flake", "quake", "snake", "stake",
  "share", "blare", "flare", "glare", "snare", "spare", "stare",
  "sharp", "harp",
  "sheep", "sleep", "steep", "sweep",
  "sheet", "fleet", "greet", "sleet", "sweet", "tweet",
  "shelf", "shell",
  "shift", "drift", "swift", "thrift",
  "shine", "brine", "dine", "swine", "twine", "whine",
  "shirt", "skirt", "flirt",
  "shock", "block", "clock", "flock", "knock", "stock",
  "shore", "snore", "spore", "store", "swore",
  "short", "court", "snort", "sport",
  "shout", "clout", "scout", "snout", "spout", "stout", "trout",
  "sight", "fight", "light", "might", "night", "right", "tight",
  "eight",
  "since", "mince", "prince", "rinse", "wince",
  "skill", "chill", "drill", "frill", "grill", "quill", "spill",
  "still", "swill", "trill",
  "sleep", "creep", "sheep", "steep", "sweep",
  "slice", "price", "spice", "twice",
  "slide", "bride", "glide", "guide", "pride",
  "smart", "chart", "heart", "start",
  "smell", "dwell", "shell", "spell", "swell",
  "smile", "agile", "exile", "while",
  "smoke", "broke", "choke", "spoke", "stoke", "stove", "woke",
  "solve", "valve", "salve",
  "sound", "bound", "found", "hound", "mound", "pound", "round",
  "wound",
  "south", "mouth", "youth",
  "space", "brace", "grace", "place", "trace",
  "spare", "blare", "flare", "glare", "share", "snare", "stare",
  "speak", "break", "freak", "sneak", "steak", "tweak", "wreak",
  "speed", "bleed", "breed", "creed", "greed", "steed",
  "spell", "dwell", "shell", "smell", "swell",
  "spend", "blend", "fiend", "trend",
  "spike", "spice", "spite", "spine", "spire",
  "spine", "swine", "twine", "whine",
  "spite", "quite", "smite", "white", "write",
  "split", "spilt",
  "spoke", "broke", "choke", "smoke", "stoke", "woken",
  "spoon", "broom", "bloom", "gloom", "groom",
  "sport", "court", "short", "snort",
  "spray", "stray", "array",
  "stack", "black", "clack", "crack", "knack", "shack", "slack",
  "smack", "snack", "track", "whack",
  "staff", "bluff", "cliff", "scoff", "sniff", "stuff",
  "stage", "gauge", "image", "usage",
  "stair", "chair", "flair",
  "stake", "brake", "drake", "flake", "quake", "shake", "snake",
  "stale", "scale", "shale", "whale",
  "stall", "shall", "small",
  "stamp", "champ", "clamp", "cramp", "swamp", "tramp",
  "stand", "bland", "brand", "gland", "grand",
  "stare", "blare", "flare", "glare", "share", "snare", "spare",
  "start", "chart", "heart", "smart",
  "state", "crate", "grate", "plate", "skate", "slate",
  "steak", "break", "freak", "sneak", "speak", "tweak", "wreak",
  "steal", "ideal", "medal",
  "steam", "cream", "dream", "gleam",
  "steel", "kneel", "wheel",
  "steep", "creep", "sheep", "sleep", "sweep",
  "steer", "cheer", "sheer",
  "stern", "learn",
  "stick", "brick", "click", "flick", "prick", "quick", "slick",
  "thick", "trick",
  "still", "chill", "drill", "frill", "grill", "quill", "skill",
  "spill", "swill", "trill",
  "stock", "block", "clock", "flock", "knock", "shock",
  "stone", "clone", "ozone", "phone", "prone", "scone", "shone",
  "store", "shore", "snore", "spore", "swore",
  "storm", "charm",
  "story", "glory", "ivory", "privy",
  "stout", "clout", "scout", "shout", "snout", "spout", "trout",
  "stove", "above", "drove", "glove", "grove", "prove",
  "strip", "drip",
  "stuck", "chuck", "cluck", "pluck", "truck",
  "study", "buddy", "muddy", "ruddy",
  "stuff", "bluff", "cliff", "scoff", "sniff",
  "stung", "clung", "flung", "slung", "swung", "wrung", "young",
  "style", "agile", "exile", "smile", "while",
  "sugar", "lunar", "radar",
  "suite", "brute", "flute", "route",
  "super", "upper", "viper",
  "surge", "gorge", "large", "merge", "purge", "verge",
  "swear", "shear", "smear", "spear",
  "sweep", "creep", "sheep", "sleep", "steep",
  "sweet", "fleet", "greet", "sheet", "sleet", "tweet",
  "swift", "drift", "shift",
  "swing", "bring", "cling", "fling", "sling", "sting", "thing",
  "wring",
  "sword", "world",
  "table", "cable", "fable", "sable", "stable",
  "teach", "beach", "leach", "peach", "reach",
  "their", "chair", "stair",
  "there", "where",
  "thick", "brick", "click", "flick", "prick", "quick", "slick",
  "stick", "trick",
  "thing", "bring", "cling", "fling", "sling", "sting", "swing",
  "wring",
  "think", "blink", "brink", "clink", "drink", "shrink",
  "those", "chose", "close", "whose",
  "three", "agree",
  "tiger", "cider", "diner", "finer", "hiker", "liner", "liter",
  "miner", "miser", "river", "rider", "timer", "viper", "wider",
  "tight", "fight", "light", "might", "night", "right", "sight",
  "eight",
  "tired", "fired", "hired", "mired", "wired",
  "today", "decay", "delay", "relay", "repay",
  "total", "fatal", "focal", "legal", "local", "loyal", "medal",
  "metal", "modal", "moral", "naval", "pedal", "penal", "renal",
  "rival", "royal", "rural", "tidal", "tonal", "trial", "usual",
  "vital", "vocal",
  "touch", "couch", "pouch", "vouch",
  "tough", "cough", "dough", "rough",
  "tower", "bower", "lower", "mower", "power", "sower",
  "toxic", "basic", "manic", "panic", "sonic", "tonic", "topic",
  "trace", "brace", "grace", "place", "space",
  "track", "black", "clack", "crack", "knack", "shack", "slack",
  "smack", "snack", "stack", "whack",
  "trade", "blade", "grade", "shade", "spade",
  "trail", "frail", "grail", "snail",
  "train", "brain", "chain", "drain", "grain", "plain", "slain",
  "stain",
  "trash", "brash", "clash", "crash", "flash", "gnash", "slash",
  "smash", "stash",
  "treat", "cheat", "great", "sweat", "wheat",
  "trend", "blend", "fiend", "spend",
  "trial", "final", "rival", "tidal", "viral", "vital",
  "tribe", "bribe", "scribe",
  "trick", "brick", "click", "flick", "prick", "quick", "slick",
  "stick", "thick",
  "troop", "droop", "snoop", "scoop", "stoop", "swoop",
  "truck", "chuck", "cluck", "pluck", "stuck",
  "trunk", "chunk", "drunk", "flunk", "plunk", "skunk", "spunk",
  "stunk",
  "trust", "crust",
  "truth", "booth", "south", "tooth", "youth",
  "under", "elder", "offer", "order", "other", "otter", "outer",
  "upper", "utter",
  "unite", "quite", "suite", "white", "write",
  "until", "anvil", "April", "pupil", "trail", "April",
  "upper", "super", "utter",
  "usual", "equal", "final", "legal", "local", "loyal", "modal",
  "moral", "nasal", "naval", "pedal", "penal", "renal", "rival",
  "royal", "rural", "tidal", "tonal", "total", "trial", "viral",
  "vital", "vocal",
  "valid", "lucid", "rapid", "rigid", "timid", "vivid",
  "value", "valve",
  "video", "vigor",
  "voice", "juice", "price", "slice", "spice", "twice",
  "watch", "catch", "hatch", "latch", "match", "patch",
  "water", "later", "cater", "eater", "hater", "mater",
  "weave", "heave", "leave",
  "wedge", "hedge", "ledge",
  "wheel", "kneel", "steel",
  "where", "there",
  "which", "hitch", "ditch", "pitch", "witch",
  "while", "agile", "exile", "smile", "style",
  "white", "quite", "smite", "spite", "write",
  "whole", "stole", "those",
  "whose", "chose", "close", "those",
  "wield", "field", "yield",
  "world", "sword",
  "worse", "horse", "curse", "nurse", "purse",
  "worst", "first", "burst",
  "worth", "forth", "north",
  "would", "could", "mould",
  "wound", "bound", "found", "hound", "mound", "pound", "round",
  "sound",
  "write", "quite", "smite", "spite", "unite", "white",
  "wrong", "prong", "among",
  "wrote", "quote",
  "yield", "field", "wield",
  "young", "clung", "flung", "slung", "stung", "swung",
  "youth", "mouth", "south",

  // Extra common words for better graph connectivity
  "bight", "clink", "cleat", "bleat", "creed", "steed",
  "treed", "fount", "trout", "gourd", "roost", "scone",
  "shorn", "frown", "noose", "sable", "robin", "swain",
  "shale", "small", "scoff", "ruddy", "spunk", "tooth",
  "snoop", "scoop", "swoop", "leach", "grail", "bribe",
  "cheat", "giver", "mange", "wince", "heady", "needy",
  "reedy", "seedy", "flirt", "swine", "twine", "spilt",
  "smite", "mould", "slick", "spire", "miner", "mired",
  "fired", "sower", "older", "dover", "rover", "tonic",
  "manic", "modal", "tract", "chuck", "wrung", "april",
  "patty", "potty",
];

// Filter only valid 5-letter lowercase words
const newWords = additionalWords
  .map(w => w.toLowerCase())
  .filter(w => w.length === 5 && /^[a-z]+$/.test(w))
  .filter(w => !existing.has(w));

const allWords = [...existing, ...newWords];
const uniqueAll = [...new Set(allWords)].filter(w => w.length === 5).sort();

console.log('Existing:', existing.size);
console.log('New words to add:', newWords.length);
console.log('Unique new words:', new Set(newWords).size);
console.log('Total unique 5-letter words:', uniqueAll.length);

// Write the final file
let output = 'const WORD_LIST: string[] = [\n';
uniqueAll.forEach(w => {
  output += `  "${w}",\n`;
});
output += '];\n\nexport const WORDS: Set<string> = new Set(WORD_LIST);\n';

fs.writeFileSync('/Users/daveconnors/wordgames/letterpress/src/data/wordList.ts', output);
console.log('Written final file to wordList.ts');
