const fs = require('fs');
const content = fs.readFileSync('/Users/daveconnors/wordgames/letterpress/src/data/wordList.ts', 'utf8');

// Extract existing words
const words = new Set(content.match(/"([a-z]+)"/g).map(w => w.replace(/"/g, '')));

// Remove problematic words: typos, proper nouns, non-words
const removeWords = [
  "thinl",  // typo
  "spain",  // proper noun
  "grobs",  // not a word
  "dover",  // proper noun
  "greek",  // proper noun
  "swiss",  // proper noun
  "april",  // proper noun (should be capitalized)
  "pluto",  // proper noun
  "fonds",  // uncommon
  "roman",  // proper noun when capitalized (but "roman" lowercase could be argued... removing to be safe)
  "imago",  // obscure
  "fagot",  // offensive
  "cozen",  // archaic
  "swain",  // archaic
  "lossy",  // very technical
  "ducal",  // obscure
  "aegis",  // keep - it's common enough
];

removeWords.forEach(w => words.delete(w));

// Additional common 5-letter words to boost the list
const moreWords = [
  // Very common words that may have been missed
  "angle", "argue", "array", "arrow", "asset",
  "attic", "audio", "audit", "awoke", "azure",

  // Common verb forms and plurals
  "acted", "added", "aimed", "asked", "baked",
  "based", "began", "began", "being", "bound",
  "broke", "built", "calls", "camps", "cents",
  "check", "child", "chose", "claim", "climb",
  "close", "comes", "costs", "could", "court",
  "cover", "dance", "death", "draft", "drawn",
  "dress", "drink", "drive", "drops", "dying",
  "ended", "enjoy", "enter", "equal", "error",
  "event", "exact", "extra", "faith", "falls",
  "fancy", "favor", "fears", "feels", "fight",
  "finds", "fires", "first", "fixed", "flesh",
  "float", "flood", "floor", "force", "forth",
  "found", "frame", "frank", "fresh", "front",
  "fruit", "fully", "funny", "given", "glass",
  "going", "grace", "grand", "grant", "grass",
  "grave", "great", "green", "grown", "guess",
  "guide", "hands", "happy", "heart", "heavy",
  "hence", "horse", "hotel", "house", "human",
  "humor", "hurry", "ideas", "image", "imply",
  "index", "inner", "input", "issue", "items",
  "joint", "judge", "keeps", "knife", "knock",
  "known", "labor", "large", "later", "laugh",
  "layer", "learn", "least", "leave", "legal",
  "level", "light", "limit", "links", "lived",
  "lives", "local", "looks", "loops", "loose",
  "lover", "lower", "lucky", "lunch", "magic",
  "major", "maker", "makes", "match", "maybe",
  "mayor", "means", "meant", "media", "mercy",
  "metal", "might", "minds", "minor", "minus",
  "model", "money", "month", "moral", "mouse",
  "mouth", "moved", "movie", "music", "names",
  "nerve", "never", "newly", "night", "noble",
  "noise", "north", "noted", "novel", "nurse",
  "occur", "ocean", "offer", "often", "order",
  "organ", "other", "ought", "outer", "owner",
  "paint", "panel", "paper", "parts", "party",
  "patch", "pause", "peace", "phase", "phone",
  "photo", "piano", "piece", "pilot", "pitch",
  "place", "plain", "plane", "plant", "plate",
  "plays", "plaza", "plead", "point", "power",
  "press", "price", "pride", "prime", "print",
  "prior", "prize", "proof", "proud", "prove",
  "psalm", "queen", "quest", "quick", "quiet",
  "quite", "quote", "radio", "raise", "range",
  "rapid", "reach", "react", "ready", "realm",
  "rebel", "reign", "relax", "reply", "rider",
  "right", "rigid", "rival", "river", "robot",
  "rocks", "rough", "round", "route", "royal",
  "rugby", "ruler", "rural", "sadly", "saint",
  "salad", "salon", "sauce", "scale", "scene",
  "scope", "score", "sense", "serve", "seven",
  "shade", "shaft", "shake", "shall", "shame",
  "shape", "share", "shark", "sharp", "sheer",
  "sheet", "shelf", "shell", "shift", "shine",
  "shirt", "shock", "shore", "short", "shout",
  "shown", "sight", "silly", "since", "sixth",
  "sixty", "sized", "skill", "sleep", "slice",
  "slide", "slope", "smart", "smell", "smile",
  "smoke", "snake", "solar", "solid", "solve",
  "sorry", "sound", "south", "space", "spare",
  "speak", "speed", "spell", "spend", "spent",
  "spite", "split", "spoke", "sport", "spray",
  "squad", "staff", "stage", "stain", "stake",
  "stand", "stare", "start", "state", "stays",
  "steal", "steam", "steel", "steep", "stern",
  "stick", "still", "stock", "stone", "stood",
  "store", "storm", "story", "stove", "strip",
  "stuck", "study", "stuff", "style", "sugar",
  "suite", "super", "surge", "swear", "sweep",
  "sweet", "swept", "swift", "swing", "sword",
  "swore", "table", "taken", "taste", "teach",
  "teeth", "thank", "theft", "their", "theme",
  "there", "these", "thick", "thief", "thing",
  "think", "third", "those", "three", "threw",
  "throw", "thumb", "tiger", "tight", "timer",
  "tired", "title", "today", "token", "topic",
  "total", "touch", "tough", "tower", "toxic",
  "trace", "track", "trade", "trail", "train",
  "trait", "trash", "treat", "trend", "trial",
  "tribe", "trick", "tried", "troop", "truck",
  "truly", "trunk", "trust", "truth", "twice",
  "twist", "typed", "ultra", "uncle", "under",
  "union", "unite", "unity", "until", "upper",
  "upset", "urban", "usage", "usual", "utter",
  "valid", "value", "valve", "vault", "verse",
  "video", "vigor", "vinyl", "viral", "virus",
  "visit", "vital", "vivid", "vocal", "voice",
  "voter", "wagon", "waist", "waste", "watch",
  "water", "weave", "wedge", "weigh", "weird",
  "whale", "wheat", "wheel", "where", "which",
  "while", "white", "whole", "whose", "wider",
  "widow", "width", "wield", "witch", "woman",
  "women", "woods", "words", "works", "world",
  "worry", "worse", "worst", "worth", "would",
  "wound", "wrath", "wrist", "write", "wrong",
  "wrote", "yacht", "yield", "young", "youth",
  "zebra",

  // Extra words for better connectivity (common patterns)
  "abled", "abort", "admit", "adopt", "adult",
  "after", "again", "agent", "agree", "ahead",
  "alarm", "album", "alert", "alien", "align",
  "alike", "alive", "alley", "allow", "alone",
  "along", "alpha", "altar", "alter", "among",
  "angel", "anger", "angry", "ankle", "apple",
  "apply", "arena", "armor", "aroma", "aside",
  "avoid", "awake", "award", "aware", "awful",

  "bacon", "badge", "badly", "baker", "basic",
  "basin", "basis", "batch", "beach", "beard",
  "beast", "begin", "below", "bench", "berry",
  "bible", "birth", "black", "blade", "blame",
  "bland", "blank", "blast", "blaze", "bleed",
  "blend", "bless", "blind", "blink", "bliss",
  "block", "blood", "bloom", "blown", "board",
  "bonus", "boost", "booth", "bound", "brain",
  "brand", "brave", "bread", "break", "breed",
  "brick", "bride", "brief", "bring", "broad",
  "brook", "brown", "brush", "buddy", "build",
  "bunch", "burst", "buyer",

  "cabin", "cable", "candy", "cargo", "carry",
  "catch", "cause", "cedar", "chain", "chair",
  "chalk", "chaos", "charm", "chart", "chase",
  "cheap", "cheat", "cheek", "cheer", "chess",
  "chest", "chief", "child", "chill", "china",
  "chunk", "civic", "civil", "claim", "clash",
  "class", "clean", "clear", "clerk", "click",
  "cliff", "climb", "cling", "clock", "clone",
  "close", "cloth", "cloud", "coach", "coast",
  "color", "comic", "coral", "could", "count",
  "court", "cover", "crack", "craft", "crane",
  "crash", "crazy", "cream", "creek", "crime",
  "crisp", "cross", "crowd", "crown", "cruel",
  "crush", "curve", "cycle",

  "daily", "dairy", "dance", "dealt", "death",
  "debug", "decay", "decoy", "delay", "delta",
  "dense", "depth", "derby", "devil", "diary",
  "dirty", "dodge", "doing", "doubt", "dough",
  "draft", "drain", "drama", "drank", "dream",
  "dress", "dried", "drift", "drill", "drink",
  "drive", "drown", "drunk", "dryer", "dying",

  "eager", "early", "earth", "eight", "elder",
  "elect", "elite", "email", "empty", "enemy",
  "enjoy", "enter", "entry", "equal", "equip",
  "error", "essay", "ethic", "event", "every",
  "exact", "exert", "exist", "extra",

  "fable", "facet", "faith", "false", "fatal",
  "fault", "feast", "fence", "ferry", "fever",
  "fiber", "field", "fifth", "fifty", "fight",
  "final", "first", "flame", "flash", "fleet",
  "flesh", "float", "flock", "flood", "floor",
  "flour", "fluid", "flush", "focal", "focus",
  "force", "forge", "forth", "forum", "found",
  "frame", "fraud", "fresh", "front", "frost",
  "fruit", "fully", "funds", "funny",

  "ghost", "giant", "given", "glass", "gleam",
  "glide", "globe", "gloom", "glory", "gloss",
  "glove", "going", "grace", "grade", "grain",
  "grand", "grant", "grape", "grasp", "grass",
  "grave", "great", "greed", "green", "greet",
  "grief", "grill", "grind", "gross", "group",
  "grove", "grown", "guard", "guess", "guest",
  "guide", "guild", "guilt",

  "habit", "happy", "harsh", "haven", "heart",
  "heavy", "hedge", "hence", "herbs", "hiker",
  "hinge", "hobby", "honor", "horse", "hotel",
  "house", "human", "humor", "hurry", "hyper",

  "ideal", "image", "imply", "inbox", "index",
  "indie", "inner", "input", "issue", "ivory",

  "jewel", "joint", "joker", "judge", "juice",

  "karma", "knack", "kneel", "knife", "knock",
  "known",

  "label", "labor", "large", "laser", "later",
  "laugh", "layer", "lease", "leave", "legal",
  "lemon", "level", "light", "limit", "linen",
  "liner", "liver", "llama", "local", "lodge",
  "logic", "loose", "lover", "lower", "loyal",
  "lucky", "lunch", "lunar", "lyric",

  "magic", "major", "maker", "manor", "maple",
  "march", "match", "maybe", "mayor", "media",
  "mercy", "merge", "merit", "metal", "meter",
  "might", "minor", "minus", "model", "money",
  "month", "moral", "motor", "mount", "mouse",
  "mouth", "movie", "music",

  "naive", "nerve", "never", "newly", "niche",
  "night", "noble", "noise", "nomad", "north",
  "noted", "novel", "nurse", "nylon",

  "occur", "ocean", "offer", "often", "olive",
  "onset", "opera", "orbit", "order", "organ",
  "other", "ought", "outer", "owner", "oxide",
  "ozone",

  "paint", "panel", "panic", "paper", "paste",
  "patch", "pause", "peace", "peach", "pearl",
  "penny", "phase", "phone", "photo", "piano",
  "piece", "pilot", "pinch", "pitch", "pixel",
  "pizza", "place", "plain", "plane", "plant",
  "plate", "plaza", "plead", "pluck", "plumb",
  "plume", "point", "polar", "porch", "pound",
  "power", "press", "price", "pride", "prime",
  "print", "prior", "prize", "probe", "prone",
  "proof", "prose", "proud", "prove", "psalm",
  "pulse", "punch", "pupil", "purse",

  "queen", "quest", "queue", "quick", "quiet",
  "quite", "quota", "quote",

  "radar", "radio", "raise", "rally", "ranch",
  "range", "rapid", "ratio", "reach", "react",
  "ready", "realm", "rebel", "refer", "reign",
  "relax", "reply", "resin", "rider", "ridge",
  "rifle", "right", "rigid", "risky", "rival",
  "river", "robot", "rocky", "round", "route",
  "royal", "rugby", "ruler", "rural",

  "sadly", "saint", "salad", "salon", "sandy",
  "sauce", "scale", "scare", "scene", "scent",
  "scope", "score", "scout", "screw", "sedan",
  "sense", "serve", "setup", "seven", "shade",
  "shaft", "shake", "shall", "shame", "shape",
  "share", "shark", "sharp", "shave", "shear",
  "sheep", "sheer", "sheet", "shelf", "shell",
  "shift", "shine", "shirt", "shock", "shore",
  "short", "shout", "shown", "shrug", "sight",
  "silly", "since", "sixth", "sixty", "sized",
  "skill", "skull", "slate", "slave", "sleep",
  "slice", "slide", "slope", "smart", "smell",
  "smile", "smith", "smoke", "snake", "solar",
  "solid", "solve", "sorry", "sound", "south",
  "space", "spare", "spark", "speak", "spear",
  "speed", "spell", "spend", "spent", "spice",
  "spike", "spine", "spite", "split", "spoke",
  "spoon", "sport", "spray", "squad", "stack",
  "staff", "stage", "stain", "stair", "stake",
  "stall", "stamp", "stand", "stare", "stark",
  "start", "state", "stays", "steak", "steal",
  "steam", "steel", "steep", "steer", "stern",
  "stick", "stiff", "still", "sting", "stink",
  "stock", "stoic", "stone", "stood", "stool",
  "store", "storm", "story", "stout", "stove",
  "strap", "straw", "stray", "strip", "stuck",
  "study", "stuff", "style", "sugar", "suite",
  "sunny", "super", "surge", "swamp", "swarm",
  "swear", "sweat", "sweep", "sweet", "swept",
  "swift", "swing", "swirl", "sword", "sworn",
  "syrup",

  "table", "taste", "teach", "teeth", "tempo",
  "tenth", "theme", "there", "thick", "thief",
  "thing", "think", "third", "thorn", "those",
  "three", "threw", "throw", "thumb", "tiger",
  "tight", "timer", "tired", "title", "today",
  "token", "topic", "total", "touch", "tough",
  "tower", "toxic", "trace", "track", "trade",
  "trail", "train", "trait", "trash", "treat",
  "trend", "trial", "tribe", "trick", "tried",
  "troop", "truck", "truly", "trunk", "trust",
  "truth", "tumor", "tuner", "tweak", "twice",
  "twist",

  "ultra", "uncle", "under", "union", "unite",
  "unity", "until", "upper", "upset", "urban",
  "usage", "usual", "utter",

  "valid", "value", "valve", "vault", "verse",
  "video", "vigor", "vinyl", "viola", "viral",
  "virus", "visit", "vista", "vital", "vivid",
  "vocal", "voice", "voter",

  "wagon", "waist", "waste", "watch", "water",
  "weary", "weave", "wedge", "weigh", "weird",
  "wheat", "wheel", "where", "which", "while",
  "white", "whole", "whose", "wider", "widow",
  "width", "wield", "witch", "woman", "works",
  "world", "worry", "worse", "worst", "worth",
  "would", "wound", "wrath", "wrist", "write",
  "wrong", "wrote",

  "yacht", "yield", "young", "youth", "zebra",

  // More supplementary common words for coverage
  "abbey", "abode", "abuse", "actor", "adore",
  "aging", "agony", "alarm", "album", "alert",
  "alibi", "alive", "aloof", "alpha", "altar",
  "amber", "amble", "amend", "ample", "amuse",
  "angst", "anime", "annex", "apron", "arena",
  "asset", "atlas", "attic", "avail", "avert",
  "awful",

  "bagel", "belly", "bible", "bikes", "birds",
  "bland", "bliss", "bloke", "bogus", "bowel",
  "brace", "brash", "brass", "bravo", "brisk",
  "brood", "broth", "brunt", "budge", "bulge",
  "bully",

  "cache", "camel", "canal", "carol", "carve",
  "cater", "cedar", "charm", "chess", "cider",
  "cigar", "civic", "civil", "clasp", "clerk",
  "cloth", "cocoa", "comet", "comma", "couch",
  "cough", "coupe", "covet", "crate", "crave",
  "crawl", "creed", "crimp", "crude", "crust",
  "cubic",

  "dairy", "daisy", "datum", "debut", "decal",
  "decor", "deity", "delve", "demon", "denim",
  "depot", "deuce", "digit", "dimly", "disco",
  "ditto", "diver", "dizzy", "donor", "donut",
  "dough", "dowdy", "drake", "dread", "drone",
  "drool", "droop", "drove", "dwarf", "dwell",

  "eagle", "easel", "eaten", "ebony", "edict",
  "eerie", "elfin", "elope", "elude", "ember",
  "emoji", "enact", "endow", "ensue", "envoy",
  "epoch", "erase", "erect", "erode", "erupt",
  "ether", "evade", "evict", "evoke", "exalt",
  "exile", "expat", "expel", "exude",

  "facet", "fable", "farce", "fauna", "feign",
  "feint", "felon", "fetch", "fiend", "filth",
  "fishy", "flair", "flake", "flank", "flare",
  "flask", "fleet", "flint", "flora", "floss",
  "fluke", "flunk", "flute", "foggy", "folly",
  "foyer", "frail", "friar", "frill", "frisk",
  "froze", "fungi", "funky", "furry", "fussy",
  "fuzzy",

  "gaily", "gamma", "gaunt", "gauze", "gavel",
  "genre", "giddy", "gland", "glare", "glaze",
  "glean", "glint", "gloat", "gnome", "goose",
  "gorge", "graft", "graph", "grate", "gravy",
  "graze", "grime", "gripe", "groan", "groin",
  "groom", "grope", "grout", "growl", "gruel",
  "gruff", "grunt", "guava", "guise", "gulch",
  "gully",

  "haiku", "hardy", "haste", "hasty", "hatch",
  "haunt", "haven", "havoc", "hazel", "heave",
  "hefty", "heist", "helix", "hello", "heron",
  "hinge", "hippo", "hitch", "hoard", "holly",
  "homer", "honey", "hound", "hover", "humid",

  "idiot", "idiom", "ivory",

  "jazzy", "jeans", "jelly", "jerky", "jiffy",
  "jolly", "joust", "juicy", "jumbo", "jumpy",

  "kayak", "kebab", "kiosk", "knack", "knead",
  "knelt", "knobs", "knoll", "knots", "koala",

  "lance", "lapel", "lapse", "larva", "laser",
  "latch", "latex", "lathe", "leafy", "leaky",
  "leapt", "lease", "leash", "ledge", "lemon",
  "lever", "lilac", "limbo", "limbs", "lingo",
  "llama", "lobby", "lodge", "lofty", "logic",
  "lotus", "lousy", "lucid", "lumen", "lumpy",
  "lunge", "lurch", "lusty",

  "macho", "macro", "mafia", "magma", "mange",
  "mango", "mania", "manic", "marsh", "matte",
  "maxim", "melee", "melon", "merge", "merit",
  "merry", "messy", "metro", "micro", "midst",
  "mirth", "miser", "misty", "modal", "modem",
  "mogul", "moist", "molar", "moldy", "moody",
  "moose", "moron", "mossy", "motel", "motto",
  "mound", "mourn", "mucus", "muddy", "mural",
  "murky", "musty", "muted",

  "nanny", "nasal", "nasty", "naval", "navel",
  "needy", "nexus", "niche", "ninja", "nobly",
  "nodal", "noisy", "nomad", "notch", "nudge",
  "nutty", "nylon", "nymph",

  "oasis", "oddly", "olive", "omega", "onset",
  "opera", "optic", "orbit", "otter", "ounce",
  "outdo", "ovary", "overt",

  "paddy", "pagan", "panda", "pasta", "pasty",
  "patio", "patty", "pecan", "pedal", "penal",
  "perch", "peril", "perky", "petal", "petty",
  "picky", "piety", "pixel", "pizza", "plaid",
  "plank", "pleat", "plumb", "plume", "plump",
  "plush", "poach", "poker", "polar", "polyp",
  "posse", "potty", "pouch", "prank", "prawn",
  "prism", "privy", "prone", "prong", "prose",
  "prowl", "proxy", "prude", "prune", "puppy",
  "purge", "pushy", "putty",

  "quack", "qualm", "quart", "query", "queue",
  "quill", "quilt", "quirk", "quota",

  "racer", "radon", "rally", "ranch", "rarer",
  "raspy", "ravel", "raven", "razor", "realm",
  "recap", "relic", "remit", "renal", "renew",
  "repay", "repel", "rerun", "reset", "retry",
  "revel", "ridge", "rifle", "rinse", "risky",
  "rivet", "rogue", "roost", "rouge", "rowdy",
  "ruins", "rumba", "rumor",

  "salsa", "salty", "salve", "saner", "satin",
  "saucy", "sauna", "savor", "savvy", "scald",
  "scalp", "scant", "scarf", "scary", "scoff",
  "scone", "scoop", "scorn", "scowl", "scram",
  "scrap", "scree", "scrub", "sedan", "seize",
  "sepia", "serif", "serum", "sever", "shady",
  "shale", "shard", "shawl", "sheen", "shire",
  "shorn", "shove", "shred", "shrew", "shrub",
  "shunt", "siege", "sigma", "silky", "sinew",
  "siren", "skimp", "skirt", "skull", "slack",
  "slain", "slang", "slant", "slash", "sleek",
  "sleet", "slick", "slime", "slimy", "sling",
  "slink", "sloth", "slump", "slurp", "smack",
  "small", "smear", "smelt", "smirk", "smite",
  "smith", "smock", "snack", "snail", "snare",
  "snarl", "sneak", "sneer", "sniff", "snoop",
  "snore", "snort", "snout", "snowy", "sober",
  "socks", "soggy", "sonar", "sonic", "sower",
  "spade", "spawn", "speck", "spiel", "spill",
  "spilt", "spire", "spook", "spore", "spout",
  "spree", "sprig", "spunk", "squat", "squid",
  "stale", "stalk", "stall", "stoic", "stoke",
  "stole", "stomp", "stool", "stoop", "stork",
  "straw", "stray", "strum", "strut", "stump",
  "stung", "stunk", "stunt", "suave", "sulky",
  "sushi", "swamp", "swath", "swell", "swill",
  "swine", "swipe", "swoop", "sworn", "swung",

  "tacit", "tacos", "taint", "tally", "talon",
  "tangy", "tardy", "tasty", "taunt", "teary",
  "tease", "teddy", "tempo", "tense", "their",
  "these", "thigh", "thrum", "tidal", "tilts",
  "timid", "tipsy", "titan", "toast", "tolls",
  "tonal", "toned", "toner", "tonic", "tooth",
  "torch", "tours", "towel", "towns", "tract",
  "tramp", "traps", "trawl", "tread", "treed",
  "trill", "trims", "trips", "trite", "troll",
  "trots", "trout", "trump", "truss", "tuber",
  "tulip", "tuned", "turbo", "turns", "tutor",
  "twang", "tweed", "tweet", "twigs", "twine",
  "twins", "twirl", "tying", "types",

  "udder", "ulcer", "umbra", "undid", "undue",
  "unfit", "unify", "unlit", "unzip", "usher",

  "vague", "valor", "vapor", "veins", "venom",
  "venue", "verbs", "verge", "vines", "viper",
  "visor", "vodka", "vogue", "volts", "vouch",
  "vowel",

  "waded", "wager", "wages", "wakes", "wales",
  "walls", "waltz", "wands", "warns", "waved",
  "waves", "weedy", "weeks", "wells", "whack",
  "wharf", "whine", "whirl", "whisk", "wince",
  "windy", "wines", "wings", "wired", "witty",
  "woken", "women", "woods", "woody", "worms",
  "woven", "wraps", "wreak", "wrest", "wring",
  "wrung",

  "yanks", "yards", "yarns", "yawns", "yearn",
  "yeast", "yours",
  "zeros", "zesty", "zoned", "zones",

  // More words that help with game connectivity
  "adder", "aider", "amber", "amble", "amine",
  "amino", "angst", "aorta", "badge", "baker",
  "balmy", "banes", "bangs", "barge", "barns",
  "baron", "basal", "basil", "baste", "bated",
  "bathe", "baton", "bawdy", "beady", "beaks",
  "beams", "beans", "bears", "beats", "bedew",
  "beech", "beers", "befit", "beige", "bells",
  "belts", "bills", "bites", "blare", "blobs",
  "blows", "blues", "bluff", "blunt", "boats",
  "bogus", "bolts", "bombs", "bones", "books",
  "boots", "booty", "borax", "borne", "bosom",
  "botch", "bowed", "bower", "boxer", "boxes",
  "braid", "brake", "bravo", "brawl", "brawn",
  "braze", "brine", "briny", "broil", "brook",
  "broom", "brute", "buggy", "bugle", "built",
  "bulky", "bunny", "burly", "burnt", "buses",

  "caddy", "cadet", "cages", "cairn", "caked",
  "cakes", "calms", "cameo", "camps", "canoe",
  "caper", "carat", "cared", "cares", "carol",
  "cases", "caves", "cells", "cents", "chafe",
  "champ", "chant", "chaps", "chewy", "chick",
  "chili", "chime", "chins", "chips", "chirp",
  "choir", "choke", "chord", "chore", "chose",
  "chuck", "churn", "cigar", "cinch", "cited",
  "clack", "clamp", "clang", "clank", "claps",
  "clash", "claws", "clays", "cleat", "click",
  "cliff", "clips", "cloak", "clock", "clods",
  "clogs", "clone", "clout", "clown", "clubs",
  "cluck", "clump", "clung", "coals", "coats",
  "cocoa", "coded", "codes", "coils", "coins",
  "colds", "colon", "colts", "combo", "comes",
  "comfy", "comma", "conch", "condo", "cones",
  "coops", "coped", "copes", "copse", "cords",
  "cores", "corny", "costs", "coupe", "coups",
  "coves", "cramp", "crank", "crawl", "creek",
  "creep", "crest", "crews", "cribs", "cries",
  "crops", "crown", "cruet", "crumb", "cuffs",
  "cumin", "curds", "cured", "curls", "curly",
  "curry", "curse",

  "daddy", "dally", "dared", "darts", "dates",
  "dawns", "deans", "debit", "debts", "decal",
  "decks", "decor", "decoy", "decry", "deeds",
  "deems", "deity", "demon", "denim", "depot",
  "detox", "deuce", "diets", "dined", "dines",
  "discs", "ditch", "ditto", "diver", "dives",
  "docks", "dodge", "dolls", "dolor", "donut",
  "doors", "doses", "doves", "downs", "dowry",
  "drags", "drake", "drape", "drawn", "draws",
  "drips", "drone", "drool", "droop", "drops",
  "dross", "drugs", "drums", "ducks", "duels",
  "duets", "dulls", "dummy", "dumps", "dunce",
  "dunes", "dunks", "duped", "dusty", "dwelt",

  "eased", "eater", "edged", "edges", "edits",
  "eight", "elbow", "ember", "emcee", "ended",
  "enema", "enjoy", "entry", "epoch", "equip",
  "essay", "ether", "ethic", "evade", "event",
  "every", "exalt", "exams", "excel", "exile",
  "exist", "expat", "expel", "exude", "exult",
  "eying",

  "faced", "faces", "faded", "fades", "fails",
  "fairy", "fakes", "false", "famed", "fangs",
  "farms", "fatty", "fault", "favor", "fears",
  "feast", "feats", "feeds", "feels", "fella",
  "fence", "ferry", "feuds", "fewer", "fiber",
  "field", "fifth", "fifty", "fills", "films",
  "fined", "finer", "fines", "fired", "fires",
  "firms", "fishy", "fists", "fixed", "fixer",
  "flags", "flake", "flaky", "flame", "flank",
  "flaps", "flash", "flask", "flats", "flaws",
  "flick", "flier", "fling", "flint", "flips",
  "flirt", "flock", "floor", "flora", "floss",
  "flour", "flows", "fluff", "fluid", "flung",
  "flute", "foams", "focal", "focus", "foils",
  "folds", "folks", "fonts", "foods", "fools",
  "forge", "forgo", "forms", "forte", "forty",
  "forum", "fouls", "found", "fount", "foxes",
  "frail", "frame", "frank", "fraud", "freak",
  "freed", "fries", "frisk", "frock", "frogs",
  "front", "frost", "frown", "fruit", "fuels",
  "fumes", "funds", "fungi", "funky", "fused",
  "fuses",

  "gains", "games", "gangs", "gaped", "gases",
  "gates", "gauge", "gazed", "gazer", "gears",
  "geeks", "genes", "genie", "germs", "ghost",
  "gifts", "giddy", "girls", "given", "giver",
  "gives", "glade", "glare", "glass", "glaze",
  "gleam", "glean", "glide", "glint", "globe",
  "gloom", "glory", "gloss", "glove", "glued",
  "glyph", "gnash", "goals", "goats", "godly",
  "gonna", "goods", "goofy", "goose", "gorge",
  "gourd", "grace", "grade", "graft", "grail",
  "grain", "grand", "grant", "grape", "graph",
  "grasp", "grass", "grate", "grave", "gravy",
  "greed", "green", "greet", "grief", "grill",
  "grime", "grimy", "grind", "gripe", "grips",
  "grist", "groan", "groin", "groom", "grope",
  "gross", "group", "grout", "grove", "growl",
  "grown", "grubs", "gruel", "gruff", "grunt",
  "guava", "guess", "guest", "guide", "guild",
  "guilt", "guise", "gulch", "gulls", "gully",
  "gummy", "gusto", "gusts", "gusty",

  "hacks", "haiku", "halls", "halts", "hands",
  "handy", "hangs", "happy", "hares", "harms",
  "harps", "harsh", "haste", "hasty", "hated",
  "hater", "hates", "hauls", "haunt", "haven",
  "havoc", "hawks", "hazel", "heads", "heady",
  "heals", "heaps", "heard", "heart", "heave",
  "heavy", "hedge", "heeds", "heels", "hefty",
  "heirs", "heist", "helix", "hello", "helps",
  "hence", "herbs", "herds", "heron", "hider",
  "hills", "hilly", "hinge", "hints", "hippo",
  "hired", "hires", "hitch", "hives", "hoard",
  "hobby", "holes", "holly", "homer", "homes",
  "honey", "honor", "hooks", "hoped", "hopes",
  "horns", "horse", "hosts", "hotel", "hound",
  "hours", "house", "hover", "human", "humid",
  "humor", "humps", "hunks", "hunts", "hurry",
  "hyena", "hymns", "hyper",

  "icing", "ideal", "ideas", "idiom", "idiot",
  "idled", "idols", "image", "impel", "imply",
  "inbox", "incur", "index", "indie", "inept",
  "inert", "infer", "ingot", "inner", "input",
  "inter", "intro", "irate", "issue", "items",

  "jacks", "jazzy", "jeans", "jelly", "jenny",
  "jerky", "jewel", "jiffy", "jimmy", "joint",
  "joker", "jolly", "joust", "judge", "juice",
  "juicy", "jumbo", "jumps", "jumpy", "junco",
  "juror",

  "karma", "kayak", "kebab", "keels", "keeps",
  "kicks", "kills", "kinds", "kings", "kiosk",
  "kites", "knack", "knead", "kneel", "knees",
  "knelt", "knife", "knits", "knobs", "knock",
  "knoll", "knots", "known", "knows", "koala",

  "label", "labor", "laced", "laces", "lacks",
  "laden", "ladle", "lakes", "lambs", "lamps",
  "lance", "lands", "lanes", "lapel", "lapse",
  "large", "larva", "laser", "lasts", "latch",
  "later", "latex", "lathe", "laugh", "lawns",
  "layer", "leach", "leads", "leafy", "leaks",
  "leaky", "leapt", "learn", "lease", "leash",
  "least", "leave", "ledge", "legal", "lemma",
  "lemon", "lends", "level", "lever", "licks",
  "lifts", "light", "liked", "likes", "lilac",
  "limbo", "limbs", "limes", "limit", "limps",
  "lined", "linen", "liner", "lines", "lingo",
  "links", "lions", "lists", "liter", "lived",
  "liven", "liver", "lives", "llama", "loads",
  "loafs", "loans", "lobby", "local", "locks",
  "locus", "lodge", "lofty", "logic", "login",
  "logos", "looks", "loops", "loose", "lords",
  "lorry", "loser", "lotus", "lousy", "loved",
  "lover", "lower", "loyal", "lucid", "lucky",
  "lumen", "lumps", "lumpy", "lunar", "lunch",
  "lunge", "lungs", "lurch", "lured", "lurks",
  "lusty", "lying", "lyric",
];

// Filter only valid 5-letter lowercase
moreWords.forEach(w => {
  const lower = w.toLowerCase();
  if (lower.length === 5 && /^[a-z]+$/.test(lower)) {
    words.add(lower);
  }
});

const sorted = [...words].filter(w => w.length === 5).sort();

console.log('Final unique 5-letter word count:', sorted.length);

// Write the final file
let output = 'const WORD_LIST: string[] = [\n';
sorted.forEach(w => {
  output += `  "${w}",\n`;
});
output += '];\n\nexport const WORDS: Set<string> = new Set(WORD_LIST);\n';

fs.writeFileSync('/Users/daveconnors/wordgames/letterpress/src/data/wordList.ts', output);
console.log('Written final file');
